import {
  Home05Icon,
  PlayListIcon,
  Add01Icon,
  User02Icon,
  ArrowLeft01Icon,
  SearchIcon,
  BellIcon,
  PlayIcon,
  PauseIcon,
  File02Icon,
  Download01Icon,
  GameController03Icon,
  Alert01Icon,
  ArrowReloadHorizontalIcon,
  AudioLinesIcon,
  Bookmark02Icon,
  CheckCheckIcon,
  CheckIcon,
  VolumeLowIcon,
  VolumeMute02Icon,
  Camera01Icon,
  Image02Icon,
  Comment01Icon,
  LinkForwardIcon,
  Forward02Icon,
  Share03Icon,
  SmilePlusIcon,
  // overlays
  Cancel01Icon,
  Delete02Icon,
  Mic01Icon,
  SmileIcon,
  KeyboardIcon,
  Sent02Icon,
  Location01Icon,
  Contact01Icon,
  PieChartIcon,
  Link01Icon,
  MoreHorizontalIcon,
  Copy01Icon,
  Attachment01Icon,
  ArrowUp01Icon,
  ChevronDownIcon,
  // chat list
  PinIcon,
  BellOffIcon,
  Archive01Icon,
  TrashIcon,
  CommentAdd01Icon,
  AiVideo01Icon,
  PhoneCallIcon,
  CircleDashedIcon,
  FileEmpty01Icon,
  LinkBackwardIcon,
} from "@hugeicons/core-free-icons";

// name -> Hugeicons icon. To add an icon: import it above, add a line here.
export const libraryIcons = {
  profile: User02Icon,
  back: ArrowLeft01Icon,
  search: SearchIcon,
  play: PlayIcon,
  pause: PauseIcon,
  file: File02Icon,
  download: Download01Icon,
  game: GameController03Icon,

  // tab icon
  home: Home05Icon,
  create: Add01Icon,
  reel: PlayListIcon,

  // message
  audio: AudioLinesIcon,
  check: CheckIcon,
  checkDouble: CheckCheckIcon,
  
  // post
  repost: ArrowReloadHorizontalIcon,

  // re-usable
  notifications: BellIcon,
  volume: VolumeLowIcon,
  volumeMute: VolumeMute02Icon,
  report: Alert01Icon,
  bookmark: Bookmark02Icon,
  image: Image02Icon,
  fastForward: Forward02Icon,
  forward: LinkForwardIcon,
  share: Share03Icon,
  addReaction: SmilePlusIcon,
  chats: Comment01Icon,
  sticker: FileEmpty01Icon,
  reply: LinkBackwardIcon,
  
  // overlays: sheet/dialog/menu chrome and keyboard-area panels
  close: Cancel01Icon,
  delete: Delete02Icon,
  mic: Mic01Icon,
  smile: SmileIcon,
  keyboard: KeyboardIcon,
  send: Sent02Icon,
  location: Location01Icon,
  contact: Contact01Icon,
  poll: PieChartIcon,
  link: Link01Icon,
  more: MoreHorizontalIcon,
  copy: Copy01Icon,
  attach: Attachment01Icon,
  chevronUp: ArrowUp01Icon,
  chevronDown: ChevronDownIcon,

  // chat list chrome and row previews
  pin: PinIcon,
  bellOff: BellOffIcon,
  archive: Archive01Icon,
  trash: TrashIcon,
  compose: CommentAdd01Icon,
  video: AiVideo01Icon,
  phone: PhoneCallIcon,
  viewOnce: CircleDashedIcon,
  camera: Camera01Icon,
};

// Filled icons live in IconFiller.js
export const filledIconNames = ["heart", "bookmark", "verified"];
